### ISSUE TITLE
pig the dice game

### ISSUE THREAD

**Issue by ignisilva** [veend/pig-dice#1]
## Description

2 player in the game
One player roll the dice when he quit or dice's value is 1
If quit roll dice, the player get score for one round of player's turn
If dice's value is 1, the player lose all score for one round of player's turn
When one player get 100 score, the player win.

## Tasks

- [x] game end check
- [x] role dice function
- [x] counting score
- [x] print game board
