### ISSUE TITLE
Inhwa's Todo List

### ISSUE THREAD

**Issue by 014ee** [veend/pig-dice#3]
## Description

git flow를 이용하여 팀원간 협업하며
pig the dice game을 구현해봅니다.

## Todo List

- [x] README.md 작성
- [x] 기획안/역할 분배
- [x] 프로젝트에 현 상황 표시
- [ ] 기능 구현 ~ 12/2

**Comment by 014ee** [comment]
> ### Tasks
> * [ ]  list 1
> * [ ]  list 2
> * [ ]  list 3

**Comment by 014ee** [comment]
해당 이슈 재할당 부탁드립니다~
Assignees에서 제 계정 삭제는 되는데 추가는 안되나 봅니다,,
